[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-unit-template"
version = "1.0.0"
description = "pytest Unit-Test Template."
readme = {file = "README.txt", content-type = "text/markdown"}
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
  {name = "Berk Acunas", email = "info@deponessoft.com"}
]
keywords = ["pytest", "unittest", "template"]
dependencies = [
    "pytest>=9.0.0",
]
[project.urls]
Homepage = "https://github.com/DeponesLearn/pytest-unit-template"
Repository = "https://github.com/DeponesLearn/pytest-unit-template.git"
Issues = "https://github.com/DeponesLearn/pytest-unit-template/issues"

[tool.setuptools]
platforms = ["Linux", "Windows"]
include-package-data = true
zip-safe = true 

[tool.setuptools.packages.find]
where = ["src"]
exclude = []

[tool.pytest.ini_options]
pythonpath = ["src"]